version: '3.8'

services:
  model_archiver:
    build:
      context: .
      dockerfile: Dockerfile.archiver
    container_name: heat-archiver
    volumes:
      - model_store:/home/heat/model-store

  model_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: heat-server
    volumes:
      - model_store:/home/heat/model-store
    ports:
      - "7070:7070"
      - "7071:7071"
      - "8000:8000"
      - "8001:8001"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"

volumes:
  model_store:
