version: '3.8'

services:
  archiver:
    build:
      context: ./serve
      dockerfile: Dockerfile.archiver
    container_name: heat-archiver
    volumes:
      - type: bind
        source: ./serve/checkpoints.pth
        target: /home/heat/checkpoints.pth
      - type: bind
        source: ./model-store
        target: /home/heat/model-store

  server:
    build:
      context: ./serve
      dockerfile: Dockerfile.server
    container_name: heat-server
    volumes:
      - type: bind
        source: ./model-store
        target: /home/heat/model-store
    ports:
      - "7070:7070"
      - "7071:7071"
      - "8000:8000"
      - "8001:8001"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    command: torchserve --start --ncs --model-store /home/heat/model-store --models heat=heat.mar --ts-config /home/heat/config.properties
